### ISSUE TITLE
Victory condition for an team diamonds tie

### ISSUE THREAD

**Issue by DiscipleOfShinku** [JSJitsu/ai-battle-engine#19]
Currently, if a maximum of turns is exceeded and teams have equal amounts of diamonds (a map without mines), first team always wins:
`this.winningTeam = teamDiamonds1 > teamDiamonds0 ? 1 : 0;`

Probably a result in a such case can be based on numbers of remaining participants and their total health.
Then there will be a problem with battles with an odd number of participants though.

**Comment by dtfinch** [comment]
My hero takes this into account. It's especially important on the oasis map, where there's just a well in the center, and blue wins every tie.

If it's on the red team, it needs to maintain a diamond lead, or if there are no mines, blue needs to be eradicated before time runs out.

If it's on the blue team, it's sufficient to just survive and win the tie, so it can take a safer approach.

**Comment by Asuza** [comment]
The team with the most living players be the winner makes sense to me, which might be a good solution for most cases. In the case of a skewed number of players, I'm not sure. Maybe it needs to be possible to have a tie game.

**Comment by Asuza** [comment]
Working on this in #20. Accidentally fixed it on an outdated branch, though... :sweat_smile:

**Comment by Asuza** [comment]
In order to simplify determining who the winner is, I've been wondering if each living player at the end of the game should get a diamond bonus. It would need to scale to some mine-to-player ratio, but also have a minimum bonus so it applies to maps with no diamond mines. In that case, it might be as low as 1.

This would allow all wins to be counted by diamonds rather than having to fall back on some other method for determining the winne.

That, in combination with allowing a tie game, should prevent any unfair wins.

**Comment by Asuza** [comment]
Fixed via #20.
